# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
    push:
        branches:
            - main
            - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}

    - name: fetch API dependency
      uses: actions/checkout@v4
      with:
        repository: 'RUB-Informatik-im-Bauwesen/OpenBimRL'
        ref: '9699b39bce25546b8dc8c235c90c3f7525570d6c'
        path: deps

    - name: install API dependency
      run: cd deps && mvn install && cd .. && rm -rf deps

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
